name: splitspeak
options:
  bundleIdPrefix: fun.withus
targets:
  splitspeak:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [App]
    dependencies:
      - package: SCTCore
      - package: SCTAudio
    settings:
      DEVELOPMENT_TEAM: "" # Leave empty for now, to be replaced later
  SCTAudio:
    type: framework
    platform: iOS
    sources: [Modules/SCTAudio/Sources]
  SCTCore:
    type: framework
    platform: iOS
    sources: [Modules/SCTCore/Sources]

packages:
  SCTCore:
    path: .
  SCTAudio:
    path: .
